### ISSUE TITLE
Suggestion: Pasting from Slack

### ISSUE THREAD

**Issue by rhodessteve** [mattruzicka/wordle_decoder#4]
Lots of people post their results to Slack but when copying from there, it changes the colour blocks to the emoji code for yellow/green etc. e.g.

Wordle 269 2/6
:large_yellow_square::large_yellow_square::large_green_square::white_large_square::large_green_square:
:large_green_square::large_green_square::large_green_square::large_green_square::large_green_square:

Would you be able to alter the parser to accept this?

**Comment by mattruzicka** [comment]
Certainly, in fact I already did 😄 

This should be working as of version 0.1.3 via this PR: https://github.com/mattruzicka/wordle_decoder/pull/1

You can see your currently installed version(s) via `gem list wordle_decoder` and update to the latest version with `gem update wordle_decoder`

If it's not working on the latest version (0.1.4), let me know and I'll look into it when I have time.

**Comment by rhodessteve** [comment]
Thanks! i upgraded from 0.13 to 0.14 and it does indeed work. great work! 
However, it doesnt work with High Contrast mode (pasting from Slack or directly from Wordle)

e.g.
Wordle 269 3/6*
:white_large_square::white_large_square::large_orange_square::large_blue_square::large_orange_square:
:large_blue_square::large_blue_square::large_orange_square::white_large_square::large_orange_square:
:large_orange_square::large_orange_square::large_orange_square::large_orange_square::large_orange_square:

**Comment by mattruzicka** [comment]
Finally had some time to work on this. Just released version 0.1.5 which should now work with that.

Hadn't heard of high contrast mode; Thanks for bringing it to my attention!
